// <auto-generated />
using System;
using AspAngular.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspAngular.Migrations
{
    [DbContext(typeof(AspAngularContext))]
    [Migration("20230912110258_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspAngular.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("age")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateofjoing")
                        .HasColumnType("datetime2");

                    b.Property<int>("designationID")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isMarried")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("designationID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("AspAngular.Models.designation", b =>
                {
                    b.Property<int>("designationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("designationID"));

                    b.Property<string>("mydesignation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("designationID");

                    b.ToTable("designations");
                });

            modelBuilder.Entity("AspAngular.Models.Employee", b =>
                {
                    b.HasOne("AspAngular.Models.designation", "Designation")
                        .WithMany()
                        .HasForeignKey("designationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designation");
                });
#pragma warning restore 612, 618
        }
    }
}
